"""Splice the tool's own report into the two documents that quote it (E3e card t_4c48f40a).

`docs/evidence/e3e_roles_decision.md` is written by `tools/e3e_roles_decision.py`; the card's
documents must carry *that* text rather than a transcription of it. This copies named sections out of
the generated report into the marked regions of `docs/BENCHMARKS.md` and the card's evidence document,
so a re-run of `.e3e/report.sh` + this script regenerates both.

    uv run python .e3e/splice_docs.py
"""

from __future__ import annotations

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
GENERATED = ROOT / "docs" / "evidence" / "e3e_roles_decision.md"
BENCHMARKS = ROOT / "docs" / "BENCHMARKS.md"
EVIDENCE = ROOT / "docs" / "evidence" / "e3e_role_split_t_4c48f40a.md"
START = "<!-- E3E-TABLE:START"
END = "<!-- E3E-TABLE:END -->"


def sections(text: str) -> dict[str, list[str]]:
    """`## heading` -> the lines under it (the heading itself is not part of the body)."""
    out: dict[str, list[str]] = {}
    name = ""
    for line in text.splitlines():
        if line.startswith("## "):
            name = line[3:].strip()
            out[name] = []
        elif name:
            out[name].append(line)
    return out


def trim(lines: list[str], *, drop_rule: bool = False) -> list[str]:
    body = [line for line in lines if line.strip() != "---"]
    if drop_rule:
        body = [line for line in body if not line.startswith("- rule:")]
    while body and not body[0].strip():
        body.pop(0)
    while body and not body[-1].strip():
        body.pop()
    return body


def splice(path: pathlib.Path, block: list[str]) -> None:
    text = path.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)
    if not pattern.search(text):
        raise SystemExit(f"{path}: no {START} … {END} region")
    replacement = "\n".join(
        ["<!-- E3E-TABLE:START — spliced by `.e3e/splice_docs.py` from the tool's own report",
         "     (`docs/evidence/e3e_roles_decision.md`); edit the tool, never this block. -->",
         *block, "<!-- E3E-TABLE:END -->"])
    path.write_text(pattern.sub(lambda _: replacement, text, count=1), encoding="utf-8")
    print(f"{path}: spliced {len(block)} lines between the markers")


def main() -> int:
    parts = sections(GENERATED.read_text(encoding="utf-8"))
    freeze = trim(parts["The default is frozen (the probe and the table's own re-score)"])
    cells = trim(parts["The cells"])
    pairs = trim(parts["Paired comparisons (same items, item by item)"])
    decision = trim(parts["Decision"], drop_rule=True)
    for name in ("The cells", "Paired comparisons (same items, item by item)", "Decision"):
        assert parts.get(name), f"the generated report lost its `{name}` section"

    benchmarks = [*freeze, "", "### The cells", "", *cells, "",
                  "### Paired comparisons (same items, item by item)", "", *pairs, "",
                  "### The decision", "", *decision, "",
                  "The full generated report — the policy columns, the recommendation and the caveats "
                  "the numbers carry — is `docs/evidence/e3e_roles_decision.md`, written by the tool "
                  "itself; `.e3e/report.sh` regenerates it and `.e3e/splice_docs.py` re-splices this "
                  "block."]
    evidence = [*freeze, "", "### The cells", "", *cells, "",
                "### Paired comparisons (same items, item by item)", "", *pairs, "",
                "### The decision", "", *decision, "",
                "### The recommendation", "", *trim(parts["Recommendation"]), "",
                "### The caveats the numbers carry", "", *trim(parts["Caveats the numbers carry"]), "",
                "The generated report this block was spliced from is `docs/evidence/e3e_roles_decision.md` "
                "(the tool's own output, re-generated by `.e3e/report.sh`); the machine-readable record "
                "is `docs/evidence/e3e_roles_decision.json`."]
    splice(BENCHMARKS, benchmarks)
    splice(EVIDENCE, evidence)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
